[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

# Moonbeam fork testing configuration
[profile.moonbeam]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# RPC configuration for Moonbeam fork
[rpc_endpoints]
moonbeam = "https://rpc.api.moonbeam.network"
moonriver = "https://rpc.api.moonriver.moonbeam.network"
moonbase = "https://rpc.api.moonbase.moonbeam.network"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
